/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author SergioMarquez
 */
public class ViewRentas extends javax.swing.JPanel {

    /**
     * Creates new form ViewRentas
     */
    public ViewRentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_codigo = new javax.swing.JLabel();
        jl_cliente = new javax.swing.JLabel();
        jl_pelicula = new javax.swing.JLabel();
        jl_formato = new javax.swing.JLabel();
        jl_costo = new javax.swing.JLabel();
        jl_dias = new javax.swing.JLabel();
        jl_total = new javax.swing.JLabel();
        jtf_codigo = new javax.swing.JTextField();
        jtf_cliente = new javax.swing.JTextField();
        jtf_pelicula = new javax.swing.JTextField();
        jtf_formato = new javax.swing.JTextField();
        jtf_costo = new javax.swing.JTextField();
        jtf_dias = new javax.swing.JTextField();
        jtf_total = new javax.swing.JTextField();
        jbtn_guardar = new javax.swing.JButton();

        setLayout(null);

        jl_codigo.setText("Codigo");
        add(jl_codigo);
        jl_codigo.setBounds(20, 20, 80, 20);

        jl_cliente.setText("Cliente");
        add(jl_cliente);
        jl_cliente.setBounds(20, 70, 80, 20);

        jl_pelicula.setText("Pelicula");
        add(jl_pelicula);
        jl_pelicula.setBounds(20, 110, 90, 20);

        jl_formato.setText("Formato");
        add(jl_formato);
        jl_formato.setBounds(20, 150, 90, 20);

        jl_costo.setText("Costo");
        add(jl_costo);
        jl_costo.setBounds(20, 190, 90, 20);

        jl_dias.setText("Dias de renta");
        add(jl_dias);
        jl_dias.setBounds(20, 230, 77, 20);

        jl_total.setText("Total de la renta");
        add(jl_total);
        jl_total.setBounds(20, 270, 130, 20);
        add(jtf_codigo);
        jtf_codigo.setBounds(90, 20, 100, 20);
        add(jtf_cliente);
        jtf_cliente.setBounds(90, 70, 110, 20);
        add(jtf_pelicula);
        jtf_pelicula.setBounds(90, 110, 170, 20);
        add(jtf_formato);
        jtf_formato.setBounds(90, 150, 100, 20);
        add(jtf_costo);
        jtf_costo.setBounds(90, 190, 90, 20);
        add(jtf_dias);
        jtf_dias.setBounds(110, 230, 80, 20);
        add(jtf_total);
        jtf_total.setBounds(130, 270, 90, 20);

        jbtn_guardar.setText("Guardar");
        add(jbtn_guardar);
        jbtn_guardar.setBounds(260, 180, 100, 24);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jbtn_guardar;
    private javax.swing.JLabel jl_cliente;
    private javax.swing.JLabel jl_codigo;
    private javax.swing.JLabel jl_costo;
    private javax.swing.JLabel jl_dias;
    private javax.swing.JLabel jl_formato;
    private javax.swing.JLabel jl_pelicula;
    private javax.swing.JLabel jl_total;
    public javax.swing.JTextField jtf_cliente;
    public javax.swing.JTextField jtf_codigo;
    public javax.swing.JTextField jtf_costo;
    public javax.swing.JTextField jtf_dias;
    public javax.swing.JTextField jtf_formato;
    public javax.swing.JTextField jtf_pelicula;
    public javax.swing.JTextField jtf_total;
    // End of variables declaration//GEN-END:variables
}
